name: GitHub Action to Publish Docker Image
run-name: ${{ github.actor }} in Actions ðŸš€
on:  
    push :
        branches :
            - development
jobs:
  Build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build and tag docker image
        run : |
          docker build -t ${{secrets.USERNAME}}/action-uaspcc2024:v1 -f dockerfile .

      - name: Push to Dockerhub
        run : docker login -u ${{secrets.USERNAME}} -p ${{secrets.ACCESS_TOKEN}} && docker push ${{secrets.USERNAME}}/action-uaspcc2024:v1